steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/abiding-ion-436022-b5/myapp'
      - '.'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Update Kubernetes deployment'
    args:
      - 'set'
      - 'image'
      - 'deployment/myapp-deployment'
      - 'myapp=gcr.io/abiding-ion-436022-b5/myapp'
      - '--namespace=default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast2'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

images:
  - 'gcr.io/${PROJECT_ID}/myapp'

substitutions:
  _ZONE: 'northamerica-northeast2'
  _CLUSTER_NAME: 'my-flask-cluster'