steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/myapp:${SHORT_SHA}'
      - '.'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Update Kubernetes deployment'
    args:
      - 'set'
      - 'image'
      - 'deployment/myapp-deployment'
      - 'myapp=gcr.io/${PROJECT_ID}/myapp:${SHORT_SHA}'
      - '--namespace=default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

images:
  - 'gcr.io/${PROJECT_ID}/myapp:${SHORT_SHA}'

substitutions:
  _ZONE: 'northamerica-northeast2'
  _CLUSTER_NAME: 'my-cluster'

options:
  logging: CLOUD_LOGGING_ONLY