apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gcr.io/gcloud-auth-login-436022/my-flask-app:latest
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: gcr-json-key