apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: front-end:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: templates-volume
          mountPath: /flask_app/templates
      volumes:
      - name: templates-volume
        hostPath:
          path: ./templates
          type: DirectoryOrCreate